name: generate snake

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: karankumar-2112
          outputs: dist/snake.svg

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
